// AUTO-GENERATED by scripts/gen-wallpapers.py — do not edit by hand.
// Source: the shared AI Art library (CREDITS.csv + cards/ + avatars/).

export type MoodSlug =
  'hope'
  | 'peace'
  | 'faith'
  | 'strength'
  | 'unloved'
  | 'small'
  | 'weary'
  | 'anxious'
  | 'lonely'
  | 'sorrowful'
  | 'repentance';
export type WallpaperStyle = 'papercut' | 'cinematic' | 'renaissance';

export interface Wallpaper {
  id: string;
  ref: string;
  mood: MoodSlug;
  style: WallpaperStyle;
  title: string;
  /** full card (verse baked in), served from /public */
  card: string;
  /** square avatar crop of the art */
  avatar: string;
}

export interface Mood {
  slug: MoodSlug;
  vi: string;
  en: string;
  emoji: string;
}

export const MOODS: Mood[] = [
  { slug: 'hope', vi: "Cần hy vọng", en: "Need hope", emoji: '🌅' },
  { slug: 'peace', vi: "Cần bình an", en: "Need peace", emoji: '🕊️' },
  { slug: 'faith', vi: "Đức tin & sự thật", en: "Faith & truth", emoji: '✝️' },
  { slug: 'strength', vi: "Cần sức mạnh", en: "Strength & courage", emoji: '🛡️' },
  { slug: 'unloved', vi: "Cần được yêu thương", en: "Feeling unloved", emoji: '💗' },
  { slug: 'small', vi: "Thấy mình nhỏ bé", en: "Feeling small", emoji: '🌱' },
  { slug: 'weary', vi: "Mệt mỏi", en: "Weary", emoji: '😔' },
  { slug: 'anxious', vi: "Lo lắng", en: "Anxious", emoji: '😟' },
  { slug: 'lonely', vi: "Cô đơn", en: "Lonely", emoji: '🥀' },
  { slug: 'sorrowful', vi: "Buồn bã", en: "Sorrowful", emoji: '😢' },
  { slug: 'repentance', vi: "Sám hối", en: "Repentance & mercy", emoji: '🙏' },
];

export const WALLPAPERS: Wallpaper[] = [
  { id: 'candle-dark-cinematic-01', ref: "Tv 27:1", mood: 'anxious', style: 'cinematic', title: "My Light and My Salvation (cinematic)", card: '/wallpapers/candle-dark-cinematic-01.jpg', avatar: '/avatars/candle-dark-cinematic-01.jpg' },
  { id: 'folded-hands-lily-cinematic-01', ref: "Pl 4:6-7", mood: 'anxious', style: 'cinematic', title: "Folded Hands and a Lily (cinematic)", card: '/wallpapers/folded-hands-lily-cinematic-01.jpg', avatar: '/avatars/folded-hands-lily-cinematic-01.jpg' },
  { id: 'robin-sunset-cinematic-01', ref: "Mt 6:26", mood: 'anxious', style: 'cinematic', title: "Birds of the Air (cinematic)", card: '/wallpapers/robin-sunset-cinematic-01.jpg', avatar: '/avatars/robin-sunset-cinematic-01.jpg' },
  { id: 'storm-hand-cinematic-01', ref: "Mc 4:39", mood: 'anxious', style: 'cinematic', title: "Peace, Be Still (cinematic)", card: '/wallpapers/storm-hand-cinematic-01.jpg', avatar: '/avatars/storm-hand-cinematic-01.jpg' },
  { id: 'bird-providence-papercut-01', ref: "Mt 6:26", mood: 'anxious', style: 'papercut', title: "Birds of the Air", card: '/wallpapers/bird-providence-papercut-01.jpg', avatar: '/avatars/bird-providence-papercut-01.jpg' },
  { id: 'candle-steady-papercut-01', ref: "Tv 27:1", mood: 'anxious', style: 'papercut', title: "The Steady Flame", card: '/wallpapers/candle-steady-papercut-01.jpg', avatar: '/avatars/candle-steady-papercut-01.jpg' },
  { id: 'folded-hands-papercut-01', ref: "Pl 4:6-7", mood: 'anxious', style: 'papercut', title: "Folded Hands and a Lily", card: '/wallpapers/folded-hands-papercut-01.jpg', avatar: '/avatars/folded-hands-papercut-01.jpg' },
  { id: 'jesus-calming-storm-papercut-01', ref: "Mc 4:39", mood: 'anxious', style: 'papercut', title: "Peace, Be Still", card: '/wallpapers/jesus-calming-storm-papercut-01.jpg', avatar: '/avatars/jesus-calming-storm-papercut-01.jpg' },
  { id: 'armor-of-god-cinematic-01', ref: "Ep 6:11", mood: 'faith', style: 'cinematic', title: "The Armour of God", card: '/wallpapers/armor-of-god-cinematic-01.jpg', avatar: '/avatars/armor-of-god-cinematic-01.jpg' },
  { id: 'golgotha-wide-cinematic-01', ref: "Ga 3:16", mood: 'faith', style: 'cinematic', title: "Golgotha at Dusk", card: '/wallpapers/golgotha-wide-cinematic-01.jpg', avatar: '/avatars/golgotha-wide-cinematic-01.jpg' },
  { id: 'knight-banner-cinematic-01', ref: "Rm 1:16", mood: 'faith', style: 'cinematic', title: "Not Ashamed of the Gospel", card: '/wallpapers/knight-banner-cinematic-01.jpg', avatar: '/avatars/knight-banner-cinematic-01.jpg' },
  { id: 'knight-lantern-path-cinematic-01', ref: "Tv 119:105", mood: 'faith', style: 'cinematic', title: "A Lamp for My Feet (cinematic)", card: '/wallpapers/knight-lantern-path-cinematic-01.jpg', avatar: '/avatars/knight-lantern-path-cinematic-01.jpg' },
  { id: 'knight-path-cinematic-01', ref: "Ga 14:6", mood: 'faith', style: 'cinematic', title: "The Way, the Truth, the Life", card: '/wallpapers/knight-path-cinematic-01.jpg', avatar: '/avatars/knight-path-cinematic-01.jpg' },
  { id: 'lantern-hand-cinematic-01', ref: "1 Pr 3:15", mood: 'faith', style: 'cinematic', title: "A Lamp Held Out (cinematic)", card: '/wallpapers/lantern-hand-cinematic-01.jpg', avatar: '/avatars/lantern-hand-cinematic-01.jpg' },
  { id: 'race-finished-cinematic-01', ref: "2 Tm 4:7", mood: 'faith', style: 'cinematic', title: "The Race Finished", card: '/wallpapers/race-finished-cinematic-01.jpg', avatar: '/avatars/race-finished-cinematic-01.jpg' },
  { id: 'humble-lantern-papercut-01', ref: "Tv 119:105", mood: 'faith', style: 'papercut', title: "The Humble Lantern", card: '/wallpapers/humble-lantern-papercut-01.jpg', avatar: '/avatars/humble-lantern-papercut-01.jpg' },
  { id: 'lantern-lamp-papercut-01', ref: "1 Pr 3:15", mood: 'faith', style: 'papercut', title: "The Lamp Held Out", card: '/wallpapers/lantern-lamp-papercut-01.jpg', avatar: '/avatars/lantern-lamp-papercut-01.jpg' },
  { id: 'knight-archway-cinematic-01', ref: "Ga 10:9", mood: 'hope', style: 'cinematic', title: "The Open Door (cinematic)", card: '/wallpapers/knight-archway-cinematic-01.jpg', avatar: '/avatars/knight-archway-cinematic-01.jpg' },
  { id: 'knight-meadow-sunrise-cinematic-01', ref: "Rm 15:13", mood: 'hope', style: 'cinematic', title: "The God of Hope", card: '/wallpapers/knight-meadow-sunrise-cinematic-01.jpg', avatar: '/avatars/knight-meadow-sunrise-cinematic-01.jpg' },
  { id: 'knight-sunrise-peak-cinematic-01', ref: "Gr 29:11", mood: 'hope', style: 'cinematic', title: "A Future and a Hope (cinematic)", card: '/wallpapers/knight-sunrise-peak-cinematic-01.jpg', avatar: '/avatars/knight-sunrise-peak-cinematic-01.jpg' },
  { id: 'open-door-papercut-01', ref: "Ga 10:9", mood: 'hope', style: 'papercut', title: "The Open Door", card: '/wallpapers/open-door-papercut-01.jpg', avatar: '/avatars/open-door-papercut-01.jpg' },
  { id: 'winding-path-papercut-01', ref: "Gr 29:11", mood: 'hope', style: 'papercut', title: "The Winding Path", card: '/wallpapers/winding-path-papercut-01.jpg', avatar: '/avatars/winding-path-papercut-01.jpg' },
  { id: 'knight-cross-vigil-cinematic-01', ref: "Mt 28:20", mood: 'lonely', style: 'cinematic', title: "I Am With You Always (cinematic)", card: '/wallpapers/knight-cross-vigil-cinematic-01.jpg', avatar: '/avatars/knight-cross-vigil-cinematic-01.jpg' },
  { id: 'knight-moor-road-cinematic-01', ref: "Đnl 31:8", mood: 'lonely', style: 'cinematic', title: "The Road Ahead (cinematic)", card: '/wallpapers/knight-moor-road-cinematic-01.jpg', avatar: '/avatars/knight-moor-road-cinematic-01.jpg' },
  { id: 'companion-path-papercut-01', ref: "Đnl 31:8", mood: 'lonely', style: 'papercut', title: "Walking Together", card: '/wallpapers/companion-path-papercut-01.jpg', avatar: '/avatars/companion-path-papercut-01.jpg' },
  { id: 'cross-dawn-papercut-01', ref: "Mt 28:20", mood: 'lonely', style: 'papercut', title: "Cross at Dawn", card: '/wallpapers/cross-dawn-papercut-01.jpg', avatar: '/avatars/cross-dawn-papercut-01.jpg' },
  { id: 'chalice-altar-cinematic-01', ref: "Tv 23:5", mood: 'peace', style: 'cinematic', title: "My Cup Overflows (cinematic)", card: '/wallpapers/chalice-altar-cinematic-01.jpg', avatar: '/avatars/chalice-altar-cinematic-01.jpg' },
  { id: 'good-shepherd-cinematic-01', ref: "Tv 23:1", mood: 'peace', style: 'cinematic', title: "The Good Shepherd (cinematic)", card: '/wallpapers/good-shepherd-cinematic-01.jpg', avatar: '/avatars/good-shepherd-cinematic-01.jpg' },
  { id: 'knight-hillside-rest-cinematic-01', ref: "Tv 23:2", mood: 'peace', style: 'cinematic', title: "Green Pastures, Still Waters (cinematic)", card: '/wallpapers/knight-hillside-rest-cinematic-01.jpg', avatar: '/avatars/knight-hillside-rest-cinematic-01.jpg' },
  { id: 'cup-overflowing-papercut-01', ref: "Tv 23:5", mood: 'peace', style: 'papercut', title: "The Overflowing Cup", card: '/wallpapers/cup-overflowing-papercut-01.jpg', avatar: '/avatars/cup-overflowing-papercut-01.jpg' },
  { id: 'good-shepherd-papercut-01', ref: "Tv 23:1", mood: 'peace', style: 'papercut', title: "The Good Shepherd", card: '/wallpapers/good-shepherd-papercut-01.jpg', avatar: '/avatars/good-shepherd-papercut-01.jpg' },
  { id: 'good-shepherd-papercut-02', ref: "Tv 23:1", mood: 'peace', style: 'papercut', title: "The Good Shepherd (variant 2)", card: '/wallpapers/good-shepherd-papercut-02.jpg', avatar: '/avatars/good-shepherd-papercut-02.jpg' },
  { id: 'good-shepherd-papercut-03', ref: "Tv 23:1", mood: 'peace', style: 'papercut', title: "The Good Shepherd (variant 3)", card: '/wallpapers/good-shepherd-papercut-03.jpg', avatar: '/avatars/good-shepherd-papercut-03.jpg' },
  { id: 'cracked-armor-cinematic-01', ref: "2 Cr 12:9", mood: 'repentance', style: 'cinematic', title: "Light Through the Cracks", card: '/wallpapers/cracked-armor-cinematic-01.jpg', avatar: '/avatars/cracked-armor-cinematic-01.jpg' },
  { id: 'penitent-kneeling-cinematic-01', ref: "Tv 51:3", mood: 'repentance', style: 'cinematic', title: "The Penitent Knight", card: '/wallpapers/penitent-kneeling-cinematic-01.jpg', avatar: '/avatars/penitent-kneeling-cinematic-01.jpg' },
  { id: 'penitent-kneeling-papercut-01', ref: "Tv 51:3", mood: 'repentance', style: 'papercut', title: "The Penitent (papercut)", card: '/wallpapers/penitent-kneeling-papercut-01.jpg', avatar: '/avatars/penitent-kneeling-papercut-01.jpg' },
  { id: 'knight-vast-mountain-cinematic-01', ref: "Tv 8:5", mood: 'small', style: 'cinematic', title: "What Is Man (cinematic)", card: '/wallpapers/knight-vast-mountain-cinematic-01.jpg', avatar: '/avatars/knight-vast-mountain-cinematic-01.jpg' },
  { id: 'seedling-hands-cinematic-01', ref: "Tv 139:14", mood: 'small', style: 'cinematic', title: "Wonderfully Made (cinematic)", card: '/wallpapers/seedling-hands-cinematic-01.jpg', avatar: '/avatars/seedling-hands-cinematic-01.jpg' },
  { id: 'sparrows-branch-cinematic-01', ref: "Lc 12:7", mood: 'small', style: 'cinematic', title: "Two Sparrows (cinematic)", card: '/wallpapers/sparrows-branch-cinematic-01.jpg', avatar: '/avatars/sparrows-branch-cinematic-01.jpg' },
  { id: 'jesus-children-papercut-01', ref: "Mc 10:14", mood: 'small', style: 'papercut', title: "Let the Children Come", card: '/wallpapers/jesus-children-papercut-01.jpg', avatar: '/avatars/jesus-children-papercut-01.jpg' },
  { id: 'seedling-hands-papercut-01', ref: "Tv 139:14", mood: 'small', style: 'papercut', title: "Wonderfully Made", card: '/wallpapers/seedling-hands-papercut-01.jpg', avatar: '/avatars/seedling-hands-papercut-01.jpg' },
  { id: 'sparrows-papercut-01', ref: "Lc 12:7", mood: 'small', style: 'papercut', title: "Two Sparrows", card: '/wallpapers/sparrows-papercut-01.jpg', avatar: '/avatars/sparrows-papercut-01.jpg' },
  { id: 'jesus-children-renaissance-01', ref: "Mc 10:14", mood: 'small', style: 'renaissance', title: "Let the Children Come (Cổ điển)", card: '/wallpapers/jesus-children-renaissance-01.jpg', avatar: '/avatars/jesus-children-renaissance-01.jpg' },
  { id: 'dew-rose-dawn-cinematic-01', ref: "Ga 16:22", mood: 'sorrowful', style: 'cinematic', title: "Sorrow Turned to Joy (cinematic)", card: '/wallpapers/dew-rose-dawn-cinematic-01.jpg', avatar: '/avatars/dew-rose-dawn-cinematic-01.jpg' },
  { id: 'knight-cathedral-cinematic-01', ref: "Tv 34:19", mood: 'sorrowful', style: 'cinematic', title: "The Broken-Hearted (cinematic)", card: '/wallpapers/knight-cathedral-cinematic-01.jpg', avatar: '/avatars/knight-cathedral-cinematic-01.jpg' },
  { id: 'knight-shore-dawn-cinematic-01', ref: "Kh 21:4", mood: 'sorrowful', style: 'cinematic', title: "He Will Wipe Away Every Tear", card: '/wallpapers/knight-shore-dawn-cinematic-01.jpg', avatar: '/avatars/knight-shore-dawn-cinematic-01.jpg' },
  { id: 'bud-opening-papercut-01', ref: "Ga 16:22", mood: 'sorrowful', style: 'papercut', title: "The Bud Opens", card: '/wallpapers/bud-opening-papercut-01.jpg', avatar: '/avatars/bud-opening-papercut-01.jpg' },
  { id: 'wilting-rose-papercut-01', ref: "Tv 34:19", mood: 'sorrowful', style: 'papercut', title: "The Wilting Rose", card: '/wallpapers/wilting-rose-papercut-01.jpg', avatar: '/avatars/wilting-rose-papercut-01.jpg' },
  { id: 'dark-valley-cinematic-01', ref: "Tv 23:4", mood: 'strength', style: 'cinematic', title: "Through the Dark Valley", card: '/wallpapers/dark-valley-cinematic-01.jpg', avatar: '/avatars/dark-valley-cinematic-01.jpg' },
  { id: 'knight-fortress-cinematic-01', ref: "Tv 46:2", mood: 'strength', style: 'cinematic', title: "Refuge and Strength (cinematic)", card: '/wallpapers/knight-fortress-cinematic-01.jpg', avatar: '/avatars/knight-fortress-cinematic-01.jpg' },
  { id: 'knight-ridge-cinematic-01', ref: "Gs 1:9", mood: 'strength', style: 'cinematic', title: "Be Strong and Courageous", card: '/wallpapers/knight-ridge-cinematic-01.jpg', avatar: '/avatars/knight-ridge-cinematic-01.jpg' },
  { id: 'rising-up-cinematic-01', ref: "Pl 4:13", mood: 'strength', style: 'cinematic', title: "Rising Up", card: '/wallpapers/rising-up-cinematic-01.jpg', avatar: '/avatars/rising-up-cinematic-01.jpg' },
  { id: 'rock-refuge-papercut-01', ref: "Tv 46:2", mood: 'strength', style: 'papercut', title: "The Rock", card: '/wallpapers/rock-refuge-papercut-01.jpg', avatar: '/avatars/rock-refuge-papercut-01.jpg' },
  { id: 'madonna-child-cinematic-01', ref: "Is 49:15", mood: 'unloved', style: 'cinematic', title: "Madonna and Child (cinematic)", card: '/wallpapers/madonna-child-cinematic-01.jpg', avatar: '/avatars/madonna-child-cinematic-01.jpg' },
  { id: 'sacred-heart-cinematic-01', ref: "Ga 15:9", mood: 'unloved', style: 'cinematic', title: "The Sacred Heart (cinematic)", card: '/wallpapers/sacred-heart-cinematic-01.jpg', avatar: '/avatars/sacred-heart-cinematic-01.jpg' },
  { id: 'madonna-and-child-papercut-01', ref: "Is 49:15", mood: 'unloved', style: 'papercut', title: "Madonna and Child", card: '/wallpapers/madonna-and-child-papercut-01.jpg', avatar: '/avatars/madonna-and-child-papercut-01.jpg' },
  { id: 'prodigal-embrace-papercut-01', ref: "Lc 15:20", mood: 'unloved', style: 'papercut', title: "The Father Runs to Meet Him", card: '/wallpapers/prodigal-embrace-papercut-01.jpg', avatar: '/avatars/prodigal-embrace-papercut-01.jpg' },
  { id: 'sacred-heart-papercut-01', ref: "Ga 15:9", mood: 'unloved', style: 'papercut', title: "The Sacred Heart", card: '/wallpapers/sacred-heart-papercut-01.jpg', avatar: '/avatars/sacred-heart-papercut-01.jpg' },
  { id: 'madonna-child-renaissance-01', ref: "Is 49:15", mood: 'unloved', style: 'renaissance', title: "Madonna and Child (Cổ điển)", card: '/wallpapers/madonna-child-renaissance-01.jpg', avatar: '/avatars/madonna-child-renaissance-01.jpg' },
  { id: 'prodigal-embrace-renaissance-01', ref: "Lc 15:20", mood: 'unloved', style: 'renaissance', title: "The Prodigal Son (Cổ điển)", card: '/wallpapers/prodigal-embrace-renaissance-01.jpg', avatar: '/avatars/prodigal-embrace-renaissance-01.jpg' },
  { id: 'knight-burden-down-cinematic-01', ref: "Tv 55:23", mood: 'weary', style: 'cinematic', title: "Cast Your Burden", card: '/wallpapers/knight-burden-down-cinematic-01.jpg', avatar: '/avatars/knight-burden-down-cinematic-01.jpg' },
  { id: 'knight-eagle-peak-cinematic-01', ref: "Is 40:31", mood: 'weary', style: 'cinematic', title: "Wings Like Eagles (cinematic)", card: '/wallpapers/knight-eagle-peak-cinematic-01.jpg', avatar: '/avatars/knight-eagle-peak-cinematic-01.jpg' },
  { id: 'weary-rest-cinematic-01', ref: "Mt 11:28", mood: 'weary', style: 'cinematic', title: "The Knight Rests", card: '/wallpapers/weary-rest-cinematic-01.jpg', avatar: '/avatars/weary-rest-cinematic-01.jpg' },
  { id: 'eagle-dawn-papercut-01', ref: "Is 40:31", mood: 'weary', style: 'papercut', title: "Eagle at Dawn", card: '/wallpapers/eagle-dawn-papercut-01.jpg', avatar: '/avatars/eagle-dawn-papercut-01.jpg' },
  { id: 'jesus-come-to-me-papercut-01', ref: "Mt 11:28", mood: 'weary', style: 'papercut', title: "Come to Me", card: '/wallpapers/jesus-come-to-me-papercut-01.jpg', avatar: '/avatars/jesus-come-to-me-papercut-01.jpg' },
  { id: 'weary-rest-papercut-01', ref: "Mt 11:28", mood: 'weary', style: 'papercut', title: "Rest for the Weary", card: '/wallpapers/weary-rest-papercut-01.jpg', avatar: '/avatars/weary-rest-papercut-01.jpg' },
];
